version: '3'

services:
  ssm-edb:
    build:
      context: .
    labels:
      author: "danX <chenxd@bankledger.com>"
      maintainer: "danX <chenxd@bankledger.com>"
      version: "10.16"
      description: "This is the safe<->safecode middleman develop environment based on nodejs 10.15.x LTS"
    image: bankledger/ssm-edb:10.16-u16.04-1
    cap_add:
      - ALL
    env_file:
      - ./docker-env.git
    extra_hosts:
      - "rpc.safe.ssm.bankledger.com:127.0.0.1"
      - "rpc.safecode.ssm.bankledger.com:127.0.0.1"
    volumes:
      - ./docker-mount/bankledger:/home/bankledger
      - ./docker-mount/ex-work:/home/ex-work
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8880:8880"
