version: '3'

services:
  s-edb:
    build:
      context: .
    labels:
      author: "danX <chenxd@bankledger.com>"
      maintainer: "danX <chenxd@bankledger.com>"
      version: "3.0.0"
      description: "This is the base develop environment for compiling"
    image: bankledger/s-edb:3.0.0-u16.04-1
    env_file:
      - ./docker-env.git
    volumes:
      - ./docker-mount/bankledger:/home/bankledger
      - ./docker-mount/ex-work:/home/ex-work
      - /tmp/.X11-unix:/tmp/.X11-unix
#sample only
#    ports:
#      - "5554:5554"
